services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'db_data:/data/db'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongo
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongo
  frontend:
    image: kirillsch/freestyle-frontend:1.6
    #volumes:
      #- ./server/db.json:/app/db.json
    #command: ["/bin/sh", ]
    ports:  
      - "5173:5173"
    restart: unless-stopped
    depends_on :
     - backend
  backend:
    image: kirillsch/freestyle-backend:1.5
    #volumes:
     # - ./server/db.json:/app/db.json
    ports:
      - "8080:3000"
    depends_on:
      - mongo
    restart: unless-stopped
volumes:
  db_data:
    
