services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'db_data:/data/db'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongo
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongo  
  frontend:
    build: ./client
    volumes:
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build: ./server    
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped
  nginx:    
    build: ./nginx    
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped      
volumes:
  db_data:
    
