apiVersion: v1
kind: Secret
metadata:
  name: server-secret
type: Opaque
data:
  MONGODB_STRING: bW9uZ29kYjovL2tpcmlsbF9hZG1pbjpraXJpbGxfYWRtaW41NUBtb25nby1zdmM6MjcwMTcvZnJlZXN0eWxlP2F1dGhTb3VyY2U9YWRtaW4=