apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        #resources:
         # limits:
          #  memory: "521Mi"
           # cpu: "750m" 
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        env:
        {{- include "helpers.list-env-variables" . | indent 8 }}
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.livenessProbe.httpGet.path }}
            port: {{ .Values.deployment.livenessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.readinessProbe.httpGet.path }}
            port: {{ .Values.deployment.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold }}