name: Push to feature branch

on:
  push:
    branches-ignore:
      - 'main'

env: 
  TF_LOG: INFO
  TF_INPUT: false

jobs:
  check-code:
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
        working-directory: ./aws

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:  
          terraform_version: ${{ secrets.TERRAFORM_VERSION }}

      - name: Terraform Init
        id: init
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: terraform init \
          -backend-config:"bucket"=$S3_BUCKET \
          -backend-config:"key=state/terraform.tfstate" \
          -backend-config:"region"=$AWS_DEFAULT_REGION \
          -backend-config:"encrypt=true" \
          -backend-config="dynamodb_table"=$DYNAMODB_TABLE

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        if: success() || failure()
        run: terraform validate -no-color
