apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fstype: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer