apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-ebs-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-ebs
