apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-ebs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: 
      data:
        ebs-id.sh: |
        
        
          
