name: Pull Request Main

on: 
  pull_request:
    branches:
      - main

env: 
  TF_LOG: INFO
  TF_INPUT: false
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
        working-directory: ./aws

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:  
          terraform_version: ${{ secrets.TERRAFORM_VERSION }}

      - name: Terraform Init
        id: init
        run: |
          terraform init \
          -backend-config="bucket=$S3_BUCKET" \
          -backend-config="key=state/terraform.tfstate" \
          -backend-config="region=$AWS_DEFAULT_REGION" \
          -backend-config="encrypt=true" \
          -backend-config="dynamodb_table=$DYNAMODB_TABLE"

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          quiet: true
          soft_fail: false
          framework: terraform
          container_user: 1000
          output_format: github_failed_only
          skip_check: CKV_AWS_23,CKV_AWS_119

      - name: Add Plan Comment
        id: comment
        uses: actions/github-script@v7
        if: always()
        env: 
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            #### Checkov 🧪\`${{ steps.checkov.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`${process.env.PLAN}\`\`\`

            </details>

            <details><summary>Show Checkov Results</summary>

            ${process.env.CHECKOV_RESULTS}

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

            
          

        
          
        
          
